spring.application.name=sistema_biblioteca

spring.datasource.url=jdbc:mysql://localhost:3306/sistema_biblioteca
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true